version: '2.12.2'

volumes:
  pgdata:
services:
  db:
    image: postgres:alpine
    restart: unless-stopped
    environment:
      - POSTGRES_DB=netology_stocks_products
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Pderfhm86
    volumes: 
      - pgdata:/var/lib/postgresql/data
  
  backend:
    image: 9claws/compose:latest
    restart: on-failure:3
    depends_on:
      - db
    environment:
      - DB_ENGINE=django.db.backends.postgresql
      - DB_NAME=netology_stocks_products
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=Pderfhm86
    volumes:
      - ./static:/var/www/crud/static
      - ./media:/var/www/crud/media

  nginx:
    image: nginx:alpine
    restart: unless-stopped
    depends_on:
      - backend
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./static:/var/www/crud/static:ro
      - ./media:/var/www/crud/media:ro
    ports:
      - 88:80
